name: Tistory Auto Post

on:
  schedule:
    - cron: '0 3 * * *'   # 매일 9시 (KST) 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TISTORY_ID: ${{ secrets.TISTORY_ID }}
          TISTORY_PW: ${{ secrets.TISTORY_PW }}
          TISTORY_BLOG_NAME: ${{ secrets.TISTORY_BLOG_NAME }}
        run: python tistory_auto.py
